# prompt
PS1='[\h:\W]\$ '

# limit history
HISTFILESIZE=100

# delete history and quit
alias cleanup='history -c ; rm -f ~/.bash_history ; exit'

# shared configuration
[[ -f ~/.shrc_common ]] && . ~/.shrc_common

if [ -f /usr/share/bash-completion/bash_completion ]; then
  . /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi
