# prompt
PS1='[\h:\W]\$ '

# limit history
HISTFILESIZE=100

# delete history and quit
alias cleanup='history -c ; rm -f ~/.bash_history ; exit'

# shared configuration
[[ -f ~/.shrc_common ]] && . ~/.shrc_common
