# make sure we are *ksh
case $KSH_VERSION in
*MIRBSD\ KSH*|*PD\ KSH*) ;;
*) return 0 ;;
esac

# prompt
PS1="[$(hostname):\${PWD##*/}]\$ "

# enable history
export HISTFILE=~/.ksh_history

# delete history and quit
alias cleanup='rm -f ~/.ksh_history ; unset HISTFILE ; exit'

# shared configuration
[[ -f ~/.shrc_common ]] && . ~/.shrc_common

# missing emacs-style keybindings
bind '^W'=kill-region
