# sync

xrdb "$HOME/.Xresources"
setxkbmap -option caps:ctrl_modifier
xsetroot -solid rgb:11/11/11

QT_STYLE_OVERRIDE=adwaita
export QT_STYLE_OVERRIDE

which wmdocker && { wmdocker & }
which xfce4-power-manager && xfce4-power-manager

exec ssh-agent openbox
